services:
  - type: web
    name: scienceexperts-backend
    runtime: node
    region: oregon # Change to your preferred region
    plan: free # Can upgrade to starter ($7/mo) for better performance
    branch: main # Deploy from main branch
    buildCommand: npm ci && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false # Set in Render dashboard
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 7d
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_BUCKET_NAME
        value: scienceexperts-uploads
      - key: R2_PUBLIC_URL
        sync: false
      - key: RAZORPAY_MODE
        value: sandbox
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: Science Experts
      - key: BACKEND_URL
        sync: false 
      - key: FRONTEND_URL
        sync: false

    # Health check endpoint
    healthCheckPath: /api/health

    # Auto-deploy on git push
    autoDeploy: true

    # Build and deployment settings
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - nest-cli.json
