export const ERRORS = {
  ERROR_CREATING_USER: 'Error Creating User',
  ERROR_FETCHING_USERS: 'Error Fetching Users',
  ERROR_FETCHING_USER: 'Error Fetching User',
  ERROR_UPDATING_USER: 'Error Updating User',
  ERROR_DELETING_USER: 'Error Deleting User',
  ERROR_USER_NOT_FOUND: 'User Not Found',
  
  ERROR_FETCHING_DASHBOARD_DETAILS: 'Error Fetching Dashboard Details',
  
  ERROR_FETCHING_TUTORS: 'Error Fetching Tutors',
  ERROR_FETCHING_TUTOR: 'Error Fetching Tutor',

  ERROR_ID_NOT_PROVIDED: 'ID Not Provided',
  ERROR_INVALID_REFERRAL_CODE: 'Referral Code is Invalid',

  ERROR_USER_ALREADY_EXISTS: 'Email Already Exists',
  ERROR_EMAIL_NOT_FOUND: 'Email Must be Provided',
  ERROR_FETCHING_USER_BY_EMAIL: 'Error Fetching User by Email',

  ERROR_CREATING_COURSE: 'Error Creating Course',
  ERROR_FETCHING_COURSES: 'Error Fetching Courses',
  ERROR_FETCHING_COURSE: 'Error Fetching Course',
  ERROR_UPDATING_COURSE: 'Error Updating Course',
  ERROR_DELETING_COURSE: 'Error Deleting Course',
  ERROR_COURSE_NOT_FOUND: 'Course Not Found',

  ERROR_CREATING_MODULE: 'Error Creating Module',
  ERROR_FETCHING_MODULES: 'Error Fetching Modules',
  ERROR_FETCHING_MODULE: 'Error Fetching Module',
  ERROR_UPDATING_MODULE: 'Error Updating Module',
  ERROR_DELETING_MODULE: 'Error Deleting Module',
  ERROR_MODULE_NOT_FOUND: 'Module Not Found',

  ERROR_CREATING_MATERIAL: 'Error Creating Material',
  ERROR_FETCHING_MATERIALS: 'Error Fetching Materials',
  ERROR_FETCHING_MATERIAL: 'Error Fetching Material',
  ERROR_UPDATING_MATERIAL: 'Error Updating Material',
  ERROR_DELETING_MATERIAL: 'Error Deleting Material',
  ERROR_MATERIAL_NOT_FOUND: 'Material Not Found',

  ERROR_CREATING_BOOK: 'Error Creating Book',
  ERROR_FETCHING_BOOKS: 'Error Fetching Books',
  ERROR_FETCHING_BOOK: 'Error Fetching Book',
  ERROR_UPDATING_BOOK: 'Error Updating Book',
  ERROR_DELETING_BOOK: 'Error Deleting Book',
  ERROR_BOOK_NOT_FOUND: 'Book Not Found',

  ERROR_CREATING_PAPER: 'Error Creating Paper',
  ERROR_FETCHING_PAPERS: 'Error Fetching Papers',
  ERROR_FETCHING_PAPER: 'Error Fetching Paper',
  ERROR_UPDATING_PAPER: 'Error Updating Paper',
  ERROR_DELETING_PAPER: 'Error Deleting Paper',
  ERROR_PAPER_NOT_FOUND: 'Paper Not Found',

  ERROR_CREATING_BLOG: 'Error Creating Blog',
  ERROR_FETCHING_BLOGS: 'Error Fetching Blogs',
  ERROR_FETCHING_BLOG: 'Error Fetching Blog',
  ERROR_UPDATING_BLOG: 'Error Updating Blog',
  ERROR_DELETING_BLOG: 'Error Deleting Blog',
  ERROR_BLOG_NOT_FOUND: 'Blog Not Found',

  ERROR_CREATING_CATEGORY: 'Error Creating Category',
  ERROR_FETCHING_CATEGORIES: 'Error Fetching Categories',
  ERROR_FETCHING_CATEGORY: 'Error Fetching Category',
  ERROR_UPDATING_CATEGORY: 'Error Updating Category',
  ERROR_DELETING_CATEGORY: 'Error Deleting Category',
  ERROR_CATEGORY_NOT_FOUND: 'Category Not Found',
  ERROR_CATEGORY_ALREADY_EXISTS: 'Category Already Exists',

  ERROR_CATEGORY_ASSIGNED_ALREADY: 'Category Already Assigned To Courses',

  ERROR_CREATING_STANDARD: 'Error Creating Standard',
  ERROR_FETCHING_STANDARDS: 'Error Fetching Standards',
  ERROR_FETCHING_STANDARD: 'Error Fetching Standard',
  ERROR_UPDATING_STANDARD: 'Error Updating Standard',
  ERROR_DELETING_STANDARD: 'Error Deleting Standard',
  ERROR_STANDARD_NOT_FOUND: 'Standard Not Found',
  ERROR_STANDARD_ALREADY_EXISTS: 'Standard Already Exists',
  ERROR_STANDARD_ASSIGNED_ALREADY: 'Standards Already Assigned To Courses',

  ERROR_CREATING_ENROLLMENT: 'Error Creating Enrollment',
  ERROR_FETCHING_ENROLLMENTS: 'Error Fetching Enrollments',
  ERROR_FETCHING_ENROLLMENT: 'Error Fetching Enrollment',
  ERROR_UPDATING_ENROLLMENT: 'Error Updating Enrollment',
  ERROR_DELETING_ENROLLMENT: 'Error Deleting Enrollment',
  ERROR_ENROLLMENT_ALREADY_EXISTS: 'Enrollment Already Exists',
  ERROR_ENROLLMENT_NOT_FOUND: 'Enrollment Not Found',

  ERROR_CREATING_PROGRESS: 'Error Creating Progress',
  ERROR_DELETING_PROGRESS: 'Error Deleting Progress',
  ERROR_PROGRESS_NOT_FOUND: 'Progress Not Found',

  ERROR_CREATING_REVIEW: 'Error Creating Review',
  ERROR_UPDATING_REVIEW: 'Error Updating Review',
  ERROR_DELETING_REVIEW: 'Error Deleting Review',
  ERROR_FETCHING_REVIEWS: 'Error Fetching Reviews',
  ERROR_REVIEW_NOT_FOUND: 'Review Not Found',

  ERROR_CREATING_LANGUAGE: 'Error Creating Language',
  ERROR_UPDATING_LANGUAGE: 'Error Updating Language',
  ERROR_DELETING_LANGUAGE: 'Error Deleting Language',
  ERROR_FETCHING_LANGUAGES: 'Error Fetching Languages',
  ERROR_LANGUAGE_NOT_FOUND: 'Language Not Found',
  ERROR_LANGUAGE_ALREADY_EXISTS: 'Language Already Exists',

  ERROR_MATERIAL_PURCHASE_ALEARDY_EXISTS: "Material Purchase Already Exists",
  ERROR_CREATING_MATERIAL_PURCHASE: "Error Creating Material Purchase",

  ERROR_BOOK_PURCHASE_ALEARDY_EXISTS: "Book Purchase Already Exists",
  ERROR_CREATING_BOOK_PURCHASE: "Error Creating Book Purchase",

  ERROR_PAPER_PURCHASE_ALEARDY_EXISTS: "Paper Purchase Already Exists",
  ERROR_CREATING_PAPER_PURCHASE: "Error Creating Paper Purchase",

  ERROR_CREATING_COLLEGE: 'Error Creating College',
  ERROR_FETCHING_COLLEGE: 'Error Fetching Colleges',
  ERROR_FETCHING_COLLEGES: 'Error Fetching College',
  ERROR_UPDATING_COLLEGE: 'Error Updating College',
  ERROR_DELETING_COLLEGE: 'Error Deleting College',
  ERROR_COLLEGE_NOT_FOUND: 'College Not Found',

  ERROR_CREATING_COLLEGE_COURSE: 'Error Creating College Course',
  ERROR_FETCHING_COLLEGE_COURSE: 'Error Fetching College Courses',
  ERROR_FETCHING_COLLEGE_COURSES: 'Error Fetching College Course',
  ERROR_UPDATING_COLLEGE_COURSE: 'Error Updating College Course',
  ERROR_DELETING_COLLEGE_COURSE: 'Error Deleting College Course',
  ERROR_COLLEGE_COURSE_NOT_FOUND: 'College Course Not Found',

  ERROR_CREATING_ADMISSION: 'Error Creating Admission',
  ERROR_FETCHING_ADMISSIONS: 'Error Fetching Admissions',
  ERROR_FETCHING_ADMISSION: 'Error Fetching Admission',
  ERROR_UPDATING_ADMISSION: 'Error Updating Admission',
  ERROR_DELETING_ADMISSION: 'Error Deleting Admission',
  ERROR_ADMISSION_NOT_FOUND: 'Admission Not Found',
};
